// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    paysystem
    (
        init => init
        addSchedule => add_schedule
        cancelSchedule => cancel_schedule
        executePayments => execute_payments
        depositFunds => deposit_funds
        getSchedule => get_schedule
        getSchedules => get_schedules
        getTransactionHistory => get_transaction_history
        getBalance => get_balance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
